# Generated by Django 3.2.12 on 2023-01-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0002_recipe_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='amount_teaspoons',
            new_name='amount_tablespoons',
        ),
    ]
