# Generated by Django 3.2.12 on 2023-01-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0002_review_date_added'),
        ('ration', '0003_rename_amount_teaspoons_amount_amount_tablespoons'),
    ]

    operations = [
    ]
