# Generated by Django 3.2.12 on 2023-01-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0005_auto_20230106_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='ration.Recipe'),
        ),
    ]
