# Generated by Django 4.1.4 on 2023-01-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0009_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
