# Generated by Django 3.2.12 on 2023-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0009_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='amount_tablespoons',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='amount',
            name='size',
            field=models.CharField(choices=[('S', 'Teaspoon'), ('M', 'Tablespoon'), ('L', 'Cup')], default='M', max_length=1),
        ),
    ]
