# Generated by Django 3.2.12 on 2023-01-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0010_auto_20230110_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
