# Generated by Django 3.2.12 on 2023-01-11 00:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0011_auto_20230110_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], default='B', max_length=1)),
                ('date', models.DateField(verbose_name='Meal date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.profile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.recipe')),
            ],
        ),
    ]
