# Generated by Django 3.2.12 on 2023-01-11 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0012_auto_20230111_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_calorie',
            field=models.FloatField(default=2000.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_carbohydrate',
            field=models.FloatField(default=300.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_fat',
            field=models.FloatField(default=65.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_protein',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
